#! /bin/sh

NED8=WRS_N8

EDIR=../out/gcc-release/src
EXECUTABLE=qlib

SRCDIR=/common/home/bel/matthies/lnx/whiteRabbit/omnetpp-4.2/workspace/qlib
SIMDIR=/common/home/bel/matthies/lnx/whiteRabbit/

echo $SRCDIR
echo $SIMDIR

mkdir $SIMDIR/asl723
mkdir $SIMDIR/asl724

#copy qlib to its pc specific directory to avoid file clashes
cp -r $SRCDIR/ $SIMDIR/asl723/
cp -r $SRCDIR/ $SIMDIR/asl724/

chmod +x $EDIR/$EXECUTABLE
#echo $(pwd)
#echo $(ls $EDIR)


#TODO ssh to asl723 / 724
ssh -X matthies@asl723

#TODO open in different console
#ssh -X matthies@asl724


#start run there
#./$EDIR/$EXECUTABLE -f omnetppN8minHP.ini -u Cmdenv -c $NED8
#mkdir N8HPmin
#mv *.csv N8HPmin

#TODO ssh to asl724
#start run there
#./$EDIR/$EXECUTABLE -f omnetppN8maxHP.ini -u Cmdenv -c $NED8
#mkdir N8HPmax
#mv *.csv N8HPmax
