//
// Generated file, do not edit! Created by opp_msgc 4.2 from Packet.msg.
//

#ifndef _PACKET_M_H_
#define _PACKET_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif


namespace queueing {

// cplusplus {{
#include "QueueingDefs.h"
// }}

/**
 * Class generated from <tt>Packet.msg</tt> by opp_msgc.
 * <pre>
 * message Packet
 * {
 *     @customize(true);
 *     int priority;                
 *     int size;					 
 *     simtime_t totalQueueingTime; 
 *     simtime_t totalServiceTime;  
 *     simtime_t totalDelayTime;    
 *     int queueCount;              
 *     int delayCount;              
 *     int generation;              
 * }
 * </pre>
 *
 * Packet_Base is only useful if it gets subclassed, and Packet is derived from it.
 * The minimum code to be written for Packet is the following:
 *
 * <pre>
 * class Packet : public Packet_Base
 * {
 *   private:
 *     void copy(const Packet& other) { ... }

 *   public:
 *     Packet(const char *name=NULL, int kind=0) : Packet_Base(name,kind) {}
 *     Packet(const Packet& other) : Packet_Base(other) {copy(other);}
 *     Packet& operator=(const Packet& other) {if (this==&other) return *this; Packet_Base::operator=(other); copy(other); return *this;}
 *     virtual Packet *dup() const {return new Packet(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from Packet_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(Packet);
 * </pre>
 */
class Packet_Base : public ::cMessage
{
  protected:
    int priority_var;
    int size_var;
    simtime_t totalQueueingTime_var;
    simtime_t totalServiceTime_var;
    simtime_t totalDelayTime_var;
    int queueCount_var;
    int delayCount_var;
    int generation_var;

  private:
    void copy(const Packet_Base& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Packet_Base&);
    // make constructors protected to avoid instantiation
    Packet_Base(const char *name=NULL, int kind=0);
    Packet_Base(const Packet_Base& other);
    // make assignment operator protected to force the user override it
    Packet_Base& operator=(const Packet_Base& other);

  public:
    virtual ~Packet_Base();
    virtual Packet_Base *dup() const {throw cRuntimeError("You forgot to manually add a dup() function to class Packet");}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getPriority() const;
    virtual void setPriority(int priority);
    virtual int getSize() const;
    virtual void setSize(int size);
    virtual simtime_t getTotalQueueingTime() const;
    virtual void setTotalQueueingTime(simtime_t totalQueueingTime);
    virtual simtime_t getTotalServiceTime() const;
    virtual void setTotalServiceTime(simtime_t totalServiceTime);
    virtual simtime_t getTotalDelayTime() const;
    virtual void setTotalDelayTime(simtime_t totalDelayTime);
    virtual int getQueueCount() const;
    virtual void setQueueCount(int queueCount);
    virtual int getDelayCount() const;
    virtual void setDelayCount(int delayCount);
    virtual int getGeneration() const;
    virtual void setGeneration(int generation);
};

}; // end namespace queueing

#endif // _PACKET_M_H_
